// <auto-generated />
using BlazorKursevi.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorKursevi.Server.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20220112165223_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorKursevi.Shared.Osoba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mejl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Telefon")
                        .IsUnique();

                    b.ToTable("Osobe");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Osoba");
                });

            modelBuilder.Entity("BlazorKursevi.Shared.Polaznik", b =>
                {
                    b.HasBaseType("BlazorKursevi.Shared.Osoba");

                    b.HasDiscriminator().HasValue("Polaznik");

                    b.HasData(
                        new
                        {
                            Id = -4,
                            Ime = "Qweqwe",
                            Mejl = "q@q.q",
                            Prezime = "Asdasd",
                            Telefon = "0123135"
                        },
                        new
                        {
                            Id = -5,
                            Ime = "Zxczxc",
                            Mejl = "zxc@bla.bla",
                            Prezime = "Zxczxc",
                            Telefon = "5363456346"
                        },
                        new
                        {
                            Id = -6,
                            Ime = "Lkj",
                            Mejl = "lkj@l.l",
                            Prezime = "Lkj",
                            Telefon = "34235"
                        });
                });

            modelBuilder.Entity("BlazorKursevi.Shared.Predavac", b =>
                {
                    b.HasBaseType("BlazorKursevi.Shared.Osoba");

                    b.HasDiscriminator().HasValue("Predavac");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Ime = "Pera",
                            Mejl = "p@p.p",
                            Prezime = "Peric",
                            Telefon = "12345"
                        },
                        new
                        {
                            Id = -2,
                            Ime = "Neko",
                            Mejl = "bla@bla.bla",
                            Prezime = "Nekic",
                            Telefon = "345345"
                        },
                        new
                        {
                            Id = -3,
                            Ime = "Asd",
                            Mejl = "asd@asd.asd",
                            Prezime = "Qwe",
                            Telefon = "65432"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
